server.port: 96

spring.rabbitmq.addresses: localhost:5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
spring.cloud.bus.enable: true

management.endpoints.web.exposure.include: '*'


spring.application.name: config-server
spring.cloud.config.server.git.uri: git
#配置查询路径
spring.cloud.config.server.git.searchPaths: '*'
spring.cloud.config.server.git.username: 
spring.cloud.config.server.git.password: 
spring.cloud.bus.enabled: true